CREATE OR REPLACE FUNCTION SEL_USER(BASE_ID INT)
RETURNS TABLE
(
	ID INT,
    NOME VARCHAR(50),
    EMAIL VARCHAR(60),
    PASSWORD VARCHAR(200),
    HORA_DE_CRIACAO TIMESTAMP,
    HORA_DE_ATUALIZACAO TIMESTAMP
)
LANGUAGE plpgsql  AS 
$$  
BEGIN
    RETURN QUERY
	SELECT * FROM BASE_USER as bu
    WHERE bu.ID = BASE_ID;
END
$$;
