CREATE TABLE BASE_USER (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    HORA_DE_CRIACAO TIMESTAMP NOT NULL DEFAULT NOW(),
    HORA_DE_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT NOW()
)
